apiVersion: v1
kind: Service

metadata:
  name: frontend-service
  namespace: production

spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app: react-app

  ports:
  - name: {{ .Values.frontend.ports.name }}
    port: {{ .Values.frontend.ports.port }}
    targetPort: {{ .Values.frontend.ports.targetPort }}
    protocol: {{ .Values.frontend.ports.protocol }}