apiVersion: v1
kind: Secret 
metadata:
  name: backend-secret 
  namespace: production
  labels: 
    environment: production-app
    app: food-app
    developer: suriyaprashad
type: Opaque
stringData:
  mongodb: "mongodb://database-service:27017/fooddelivery"